hdfs:
  image: sequenceiq/hadoop-docker:2.4.1
  command: /etc/bootstrap.sh -d -bash
  ports:
   - "8030-8033:8030-8033"
   - "8040:8040"
   - "8042:8042"
   - "8088:8088"
   - "49707:49707"
   - "50010:50010"
   - "50020:50020"
   - "50070:50070"
   - "50075:50075"
   - "50090:50090"
mazerunner:
  image: kbastani/neo4j-graph-analytics:latest
  links:
   - hdfs
graphdb:
  image: kbastani/docker-neo4j:latest
  ports:
   - "7474:7474"
   - "1337:1337"
  volumes:
   - /opt/data
  links:
   - mazerunner
   - hdfs
